// <auto-generated />
using GeoVision;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GeoVision.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230921170918_intialDatabaseSetup")]
    partial class intialDatabaseSetup
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.11");

            modelBuilder.Entity("GeoVision.Models.LocationGvt", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("LAT")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LNG")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("LOCATIONS_GVT");
                });
#pragma warning restore 612, 618
        }
    }
}
